
### GET TOP LOSSES
GET http://127.0.0.1:3030/currencies/top-losses
content-type: application/json

### GET INFO ACCOUNT
GET http://127.0.0.1:3030/account
content-type: application/json

### POST A LIMIT ORDER WITH THE MOST LOSE SYMBOL
POST http://127.0.0.1:3030/order/limit/currency-loser
content-type: application/json

{
	"quantity" :"1"
}

### POST A LIMIT ORDER WITH SPECIFYC SYMBOL, QUANTITY AND PRICE
POST http://127.0.0.1:3030/order/limit/
content-type: application/json

{
	"symbol": "BNBBUSD",
	"price": "272.60000000",
	"quantity" :"1"
}
